# Collector specific configuration
base_url: "https://agricultural-production-hotspots.ec.europa.eu/files/"

filename: "hotspots_ts"

dataset_names:
  ASAP-HOTSPOTS-TEST: "test-asap-hotspots"

allowed_tags:
  - "drought"
  - "climate hazards"
